// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using g19_sep490_ealds.Server.Models;

#nullable disable

namespace g19_sep490_ealds.Server.Migrations
{
    [DbContext(typeof(EaldsDbContext))]
    [Migration("20260323150726_AddStartFieldsToTasksAndRepairRecord")]
    partial class AddStartFieldsToTasksAndRepairRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AcceptanceRecord", b =>
                {
                    b.Property<int>("AcceptanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcceptanceId"));

                    b.Property<DateTime>("AcceptanceDate")
                        .HasColumnType("datetime");

                    b.Property<int>("AcceptedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcurementId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrialEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("TrialStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("AcceptanceId")
                        .HasName("PK__Acceptan__747806F6B4C75151");

                    b.HasIndex("AcceptedBy");

                    b.HasIndex("ProcurementId");

                    b.ToTable("AcceptanceRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Approval", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<int>("ApprovedRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ApprovedUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.HasKey("ApprovalId")
                        .HasName("PK__Approval__328477F426B63B6B");

                    b.HasIndex("ApprovedRoleId");

                    b.HasIndex("ApprovedUserId");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("StepId");

                    b.ToTable("Approval", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("InUseDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("AssetId")
                        .HasName("PK__Asset__43492352E67F3D08");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "Code" }, "UQ__Asset__A25C5AA73764417A")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Asset__A25C5AA75E51F3B6")
                        .IsUnique();

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetCapitalization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CapitalizedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapitalizedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CapitalizedBy");

                    b.ToTable("AssetCapitalization");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__AssetCat__19093A0BBD9AABBB");

                    b.ToTable("AssetCategory", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetLifeCycle", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ActorRoleId")
                        .HasColumnType("int");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RelatedEntityId")
                        .HasColumnType("int");

                    b.Property<int>("RelatedEntityType")
                        .HasColumnType("int");

                    b.HasKey("AuditId")
                        .HasName("PK__AssetLif__A17F2398D8AAD078");

                    b.HasIndex("ActorRoleId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetLifeCycle", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("LocationId")
                        .HasName("PK__AssetLoc__E7FEA497FCEA8382");

                    b.HasIndex("AssetId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("AssetLocation", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetRequest", b =>
                {
                    b.Property<int>("AssetRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetRequestId"));

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AssetRequestId")
                        .HasName("PK__AssetReq__0CA9D3840B64CC53");

                    b.HasIndex("AssetId");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("AssetRequest", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetRequestRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("ActionByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ActionRoleId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("RecordId")
                        .HasName("PK__AssetReq__FBDF78E9FDA92C09");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("ActionRoleId");

                    b.HasIndex("AssetRequestId");

                    b.ToTable("AssetRequestRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetType", b =>
                {
                    b.Property<int>("AssetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetTypeId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AssetTypeId")
                        .HasName("PK__AssetTyp__FD33C2C25C7997D4");

                    b.HasIndex("CategoryId");

                    b.ToTable("AssetType", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("UsageId")
                        .HasName("PK__AssetUsa__29B197202990F957");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssetUsage", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED77FCD9A8");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DepreciationPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SalvageValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UsefullLifeMonths")
                        .HasColumnType("int");

                    b.HasKey("PolicyId")
                        .HasName("PK__Deprecia__2E1339A4DBD75EB5");

                    b.ToTable("DepreciationPolicy", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DiposalRecord", b =>
                {
                    b.Property<int>("DiposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiposalId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiposalDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DiposalMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("DiposalValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExecutedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiposalId")
                        .HasName("PK__DiposalR__EF94B94CAAD0B945");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("ExecutedBy");

                    b.ToTable("DiposalRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProcurementId")
                        .HasColumnType("int");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DocumentId")
                        .HasName("PK__Document__1ABEEF0FA851738F");

                    b.HasIndex("ProcurementId");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DrepreciationRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<decimal>("AccumulatedDepreciation")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("DepreciationAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingValue")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RecordId")
                        .HasName("PK__Drepreci__FBDF78E9C90EFE9C");

                    b.HasIndex("AssetId");

                    b.HasIndex("PolicyId");

                    b.ToTable("DrepreciationRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F119EA8424A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryDiscrepancy", b =>
                {
                    b.Property<int>("DiscrepancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscrepancyId"));

                    b.Property<string>("ActualCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActualLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ActualUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("BookCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("BookUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("BookValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DiscrepancyType")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("DiscrepancyId")
                        .HasName("PK__Inventor__7462A89253901749");

                    b.HasIndex("ActualLocationId");

                    b.HasIndex("ActualUserId");

                    b.HasIndex("BookLocationId");

                    b.HasIndex("BookUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("InventoryDiscrepancy", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("ActualCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActualLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ActualUserId")
                        .HasColumnType("int");

                    b.Property<int>("CheckedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateCheckCompleted")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsFound")
                        .HasColumnType("bit");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("RecordId")
                        .HasName("PK__Inventor__FBDF78E9EA25DCF8");

                    b.HasIndex("ActualLocationId");

                    b.HasIndex("ActualUserId");

                    b.HasIndex("CheckedBy");

                    b.HasIndex("TaskId");

                    b.ToTable("InventoryRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventorySession", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__Inventor__C9F49290BE3C907A");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Code" }, "UQ__Inventor__A25C5AA78FAD898D")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Inventor__A25C5AA7BFABD97D")
                        .IsUnique();

                    b.ToTable("InventorySession", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaskId")
                        .HasName("PK__Inventor__7C6949B117E656E9");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SessionId");

                    b.ToTable("InventoryTask", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenaceTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<int>("AssignTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ExpectedCompletionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LocationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaskId")
                        .HasName("PK__Maintena__7C6949B1AA925102");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("AssignTo");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ScheduleId");

                    b.ToTable("MaintenaceTask", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("ConditionAfter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("WorkPerformed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId")
                        .HasName("PK__Maintena__FBDF78E957EB0F1D");

                    b.HasIndex("TaskId");

                    b.ToTable("MaintenanceRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("IntervalHours")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Maintena__9C8A5B496EFEDE90");

                    b.HasIndex("AssetId");

                    b.HasIndex("CreateBy");

                    b.HasIndex("TemplateId");

                    b.ToTable("MaintenanceSchedule", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrequencyType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepeatIntervalUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RepeatIntervalValue")
                        .HasColumnType("int");

                    b.HasKey("TemplateId")
                        .HasName("PK__Maintena__F87ADD279992E41B");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("MaintenanceTemplate", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12625C8C38");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Procurement", b =>
                {
                    b.Property<int>("ProcurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcurementId"));

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ContractDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProcurementId")
                        .HasName("PK__Procurem__95B451EC99F6191D");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SupplierId");

                    b.ToTable("Procurement", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RepairRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("DamageCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DamageDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("RecordId")
                        .HasName("PK__RepairRe__FBDF78E9DBAA0F0C");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TaskId");

                    b.ToTable("RepairRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RepairTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("ExpectedCompletionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("datetime");

                    b.Property<string>("RepairProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TaskId")
                        .HasName("PK__RepairTa__7C6949B11CA3EB4B");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetRequestId");

                    b.ToTable("RepairTask", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RequestType", b =>
                {
                    b.Property<int>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestTypeId"));

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("RequestTypeId")
                        .HasName("PK__RequestT__4D328B839803B9F3");

                    b.HasIndex("WorkflowId");

                    b.ToTable("RequestType", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE1ABA6BB0F6");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__4BE666B4C484C0AA");

                    b.HasIndex(new[] { "Code" }, "UQ__Supplier__A25C5AA73A268A53")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Supplier__A25C5AA7B0056715")
                        .IsUnique();

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.TransferRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("AssetRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ExecuteBy")
                        .HasColumnType("int");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("FromUserId")
                        .HasColumnType("int");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime");

                    b.HasKey("RecordId")
                        .HasName("PK__Transfer__FBDF78E93D1B7772");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetRequestId");

                    b.HasIndex("ExecuteBy");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToLocationId");

                    b.HasIndex("ToUserId");

                    b.ToTable("TransferRecord", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CC4CD9659AAB");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534A0864F67")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D10534EBCFA9A1")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.WarehouseAsset", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WarehouseId")
                        .HasName("PK__Warehous__2608AFF9C170F644");

                    b.ToTable("WarehouseAsset", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Workflow", b =>
                {
                    b.Property<int>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkflowId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WorkflowId")
                        .HasName("PK__Workflow__5704A66A5F7ECD21");

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.WorkflowStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<bool>("IsFinalStep")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("StepId")
                        .HasName("PK__Workflow__24343357E49AFA53");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowStep", (string)null);
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AcceptanceRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.User", "AcceptedByNavigation")
                        .WithMany("AcceptanceRecords")
                        .HasForeignKey("AcceptedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Acceptanc__Accep__07C12930");

                    b.HasOne("g19_sep490_ealds.Server.Models.Procurement", "Procurement")
                        .WithMany("AcceptanceRecords")
                        .HasForeignKey("ProcurementId")
                        .IsRequired()
                        .HasConstraintName("FK__Acceptanc__Accep__06CD04F7");

                    b.Navigation("AcceptedByNavigation");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Approval", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Role", "ApprovedRole")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovedRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Approval__Approv__68487DD7");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ApprovedUser")
                        .WithMany("Approvals")
                        .HasForeignKey("ApprovedUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Approval__Approv__6754599E");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Approval__AssetR__66603565");

                    b.HasOne("g19_sep490_ealds.Server.Models.WorkflowStep", "Step")
                        .WithMany("Approvals")
                        .HasForeignKey("StepId")
                        .IsRequired()
                        .HasConstraintName("FK__Approval__StepId__693CA210");

                    b.Navigation("ApprovedRole");

                    b.Navigation("ApprovedUser");

                    b.Navigation("AssetRequest");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Asset", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Asset__AssetType__5BE2A6F2");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("Assets")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Asset__CreatedBy__5DCAEF64");

                    b.HasOne("g19_sep490_ealds.Server.Models.WarehouseAsset", "Warehouse")
                        .WithMany("Assets")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__Asset__Warehouse__5CD6CB2B");

                    b.Navigation("AssetType");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetCapitalization", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("AssetCapitalizations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CapitalizedByNavigation")
                        .WithMany("AssetCapitalizations")
                        .HasForeignKey("CapitalizedBy");

                    b.Navigation("Asset");

                    b.Navigation("CapitalizedByNavigation");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetLifeCycle", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Role", "ActorRole")
                        .WithMany("AssetLifeCycles")
                        .HasForeignKey("ActorRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetLife__Actor__76969D2E");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ActorUser")
                        .WithMany("AssetLifeCycles")
                        .HasForeignKey("ActorUserId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetLife__Actor__75A278F5");

                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("AssetLifeCycles")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetLife__Occur__74AE54BC");

                    b.Navigation("ActorRole");

                    b.Navigation("ActorUser");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetLocation", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("AssetLocations")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetLoca__Asset__6FE99F9F");

                    b.HasOne("g19_sep490_ealds.Server.Models.Department", "Department")
                        .WithMany("AssetLocations")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetLoca__Depar__70DDC3D8");

                    b.Navigation("Asset");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetRequest", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("AssetRequests")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("FK__AssetRequ__Asset__6383C8BA");

                    b.HasOne("g19_sep490_ealds.Server.Models.RequestType", "RequestType")
                        .WithMany("AssetRequests")
                        .HasForeignKey("RequestTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetRequ__Reque__628FA481");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "User")
                        .WithMany("AssetRequests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetRequ__UserI__619B8048");

                    b.Navigation("Asset");

                    b.Navigation("RequestType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetRequestRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ActionByUser")
                        .WithMany("AssetRequestRecords")
                        .HasForeignKey("ActionByUserId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetRequ__Actio__1AD3FDA4");

                    b.HasOne("g19_sep490_ealds.Server.Models.Role", "ActionRole")
                        .WithMany("AssetRequestRecords")
                        .HasForeignKey("ActionRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetRequ__Actio__1BC821DD");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("AssetRequestRecords")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetRequ__Asset__19DFD96B");

                    b.Navigation("ActionByUser");

                    b.Navigation("ActionRole");

                    b.Navigation("AssetRequest");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetType", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetCategory", "Category")
                        .WithMany("AssetTypes")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetType__Categ__5629CD9C");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetUsage", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("AssetUsages")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetUsag__Asset__6C190EBB");

                    b.HasOne("g19_sep490_ealds.Server.Models.Employee", "Employee")
                        .WithMany("AssetUsages")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__AssetUsag__Emplo__6D0D32F4");

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Department", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("Departments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Departmen__Updat__4222D4EF");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DiposalRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("DiposalRecords")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__DiposalRe__Asset__123EB7A3");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("DiposalRecords")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__DiposalRe__Asset__1332DBDC");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ExecutedByNavigation")
                        .WithMany("DiposalRecords")
                        .HasForeignKey("ExecutedBy")
                        .IsRequired()
                        .HasConstraintName("FK__DiposalRe__Execu__14270015");

                    b.Navigation("Asset");

                    b.Navigation("AssetRequest");

                    b.Navigation("ExecutedByNavigation");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Document", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Procurement", "Procurement")
                        .WithMany("Documents")
                        .HasForeignKey("ProcurementId")
                        .IsRequired()
                        .HasConstraintName("FK__Document__Procur__03F0984C");

                    b.Navigation("Procurement");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DrepreciationRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("DrepreciationRecords")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Dreprecia__Asset__0E6E26BF");

                    b.HasOne("g19_sep490_ealds.Server.Models.DepreciationPolicy", "Policy")
                        .WithMany("DrepreciationRecords")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__Dreprecia__Polic__0F624AF8");

                    b.Navigation("Asset");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Employee", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("EmployeeCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Employee__Create__47DBAE45");

                    b.HasOne("g19_sep490_ealds.Server.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Employee__Depart__46E78A0C");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "User")
                        .WithMany("EmployeeUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Employee__UserId__45F365D3");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryDiscrepancy", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetLocation", "ActualLocation")
                        .WithMany("InventoryDiscrepancyActualLocations")
                        .HasForeignKey("ActualLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Actua__55F4C372");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ActualUser")
                        .WithMany("InventoryDiscrepancyActualUsers")
                        .HasForeignKey("ActualUserId")
                        .HasConstraintName("FK__Inventory__Actua__57DD0BE4");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetLocation", "BookLocation")
                        .WithMany("InventoryDiscrepancyBookLocations")
                        .HasForeignKey("BookLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__BookL__55009F39");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "BookUser")
                        .WithMany("InventoryDiscrepancyBookUsers")
                        .HasForeignKey("BookUserId")
                        .HasConstraintName("FK__Inventory__BookU__56E8E7AB");

                    b.HasOne("g19_sep490_ealds.Server.Models.InventoryTask", "Task")
                        .WithMany("InventoryDiscrepancies")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__TaskI__540C7B00");

                    b.Navigation("ActualLocation");

                    b.Navigation("ActualUser");

                    b.Navigation("BookLocation");

                    b.Navigation("BookUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetLocation", "ActualLocation")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("ActualLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Actua__4F47C5E3");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ActualUser")
                        .WithMany("InventoryRecordActualUsers")
                        .HasForeignKey("ActualUserId")
                        .HasConstraintName("FK__Inventory__Actua__503BEA1C");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CheckedByNavigation")
                        .WithMany("InventoryRecordCheckedByNavigations")
                        .HasForeignKey("CheckedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Check__51300E55");

                    b.HasOne("g19_sep490_ealds.Server.Models.InventoryTask", "Task")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__DateC__4E53A1AA");

                    b.Navigation("ActualLocation");

                    b.Navigation("ActualUser");

                    b.Navigation("CheckedByNavigation");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventorySession", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetCategory", "AssetCategory")
                        .WithMany("InventorySessions")
                        .HasForeignKey("AssetCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Asset__43D61337");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetType", "AssetType")
                        .WithMany("InventorySessions")
                        .HasForeignKey("AssetTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Asset__44CA3770");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("InventorySessions")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Creat__45BE5BA9");

                    b.HasOne("g19_sep490_ealds.Server.Models.Department", "Department")
                        .WithMany("InventorySessions")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Creat__42E1EEFE");

                    b.Navigation("AssetCategory");

                    b.Navigation("AssetType");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryTask", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("InventoryTasks")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Asset__498EEC8D");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "AssignedUser")
                        .WithMany("InventoryTasks")
                        .HasForeignKey("AssignedUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Assig__4B7734FF");

                    b.HasOne("g19_sep490_ealds.Server.Models.Department", "Department")
                        .WithMany("InventoryTasks")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Depar__4A8310C6");

                    b.HasOne("g19_sep490_ealds.Server.Models.InventorySession", "Session")
                        .WithMany("InventoryTasks")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Sessi__489AC854");

                    b.Navigation("Asset");

                    b.Navigation("AssignedUser");

                    b.Navigation("Department");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenaceTask", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("MaintenaceTasks")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenac__Creat__282DF8C2");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("MaintenaceTasks")
                        .HasForeignKey("AssetRequestId")
                        .HasConstraintName("FK__Maintenac__Asset__2A164134");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "AssignToNavigation")
                        .WithMany("MaintenaceTaskAssignToNavigations")
                        .HasForeignKey("AssignTo")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenac__Assig__2B0A656D");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreateByNavigation")
                        .WithMany("MaintenaceTaskCreateByNavigations")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenac__Creat__2BFE89A6");

                    b.HasOne("g19_sep490_ealds.Server.Models.MaintenanceSchedule", "Schedule")
                        .WithMany("MaintenaceTasks")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK__Maintenac__Sched__29221CFB");

                    b.Navigation("Asset");

                    b.Navigation("AssetRequest");

                    b.Navigation("AssignToNavigation");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.MaintenaceTask", "Task")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Techn__2EDAF651");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceSchedule", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Asset__236943A5");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreateByNavigation")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("CreateBy")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Creat__245D67DE");

                    b.HasOne("g19_sep490_ealds.Server.Models.MaintenanceTemplate", "Template")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("TemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Templ__22751F6C");

                    b.Navigation("Asset");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceTemplate", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetType", "AssetType")
                        .WithMany("MaintenanceTemplates")
                        .HasForeignKey("AssetTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__IsAct__1EA48E88");

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Procurement", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("Procurements")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Procureme__Asset__7F2BE32F");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("Procurements")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK__Procureme__Creat__00200768");

                    b.HasOne("g19_sep490_ealds.Server.Models.Supplier", "Supplier")
                        .WithMany("Procurements")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__Procureme__Suppl__7E37BEF6");

                    b.Navigation("AssetRequest");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RepairRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Supplier", "Supplier")
                        .WithMany("RepairRecords")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__RepairRec__Suppl__3F115E1A");

                    b.HasOne("g19_sep490_ealds.Server.Models.RepairTask", "Task")
                        .WithMany("RepairRecords")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK__RepairRec__TaskI__3E1D39E1");

                    b.Navigation("Supplier");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RepairTask", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("RepairTasks")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__RepairTas__Asset__3A4CA8FD");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("RepairTasks")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__RepairTas__Asset__3B40CD36");

                    b.Navigation("Asset");

                    b.Navigation("AssetRequest");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RequestType", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Workflow", "Workflow")
                        .WithMany("RequestTypes")
                        .HasForeignKey("WorkflowId")
                        .IsRequired()
                        .HasConstraintName("FK__RequestTy__Workf__5165187F");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Role", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.User", "CreatedByNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Role__UpdatedBy__3B75D760");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.TransferRecord", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Asset", "Asset")
                        .WithMany("TransferRecords")
                        .HasForeignKey("AssetId")
                        .IsRequired()
                        .HasConstraintName("FK__TransferR__Asset__31B762FC");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetRequest", "AssetRequest")
                        .WithMany("TransferRecords")
                        .HasForeignKey("AssetRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__TransferR__Asset__32AB8735");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ExecuteByNavigation")
                        .WithMany("TransferRecordExecuteByNavigations")
                        .HasForeignKey("ExecuteBy")
                        .IsRequired()
                        .HasConstraintName("FK__TransferR__Execu__37703C52");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetLocation", "FromLocation")
                        .WithMany("TransferRecordFromLocations")
                        .HasForeignKey("FromLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__TransferR__FromL__339FAB6E");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "FromUser")
                        .WithMany("TransferRecordFromUsers")
                        .HasForeignKey("FromUserId")
                        .HasConstraintName("FK__TransferR__FromU__3587F3E0");

                    b.HasOne("g19_sep490_ealds.Server.Models.AssetLocation", "ToLocation")
                        .WithMany("TransferRecordToLocations")
                        .HasForeignKey("ToLocationId")
                        .IsRequired()
                        .HasConstraintName("FK__TransferR__ToLoc__3493CFA7");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "ToUser")
                        .WithMany("TransferRecordToUsers")
                        .HasForeignKey("ToUserId")
                        .HasConstraintName("FK__TransferR__ToUse__367C1819");

                    b.Navigation("Asset");

                    b.Navigation("AssetRequest");

                    b.Navigation("ExecuteByNavigation");

                    b.Navigation("FromLocation");

                    b.Navigation("FromUser");

                    b.Navigation("ToLocation");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.UserRole", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRole__RoleId__3E52440B");

                    b.HasOne("g19_sep490_ealds.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserRole__UserId__3D5E1FD2");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.WorkflowStep", b =>
                {
                    b.HasOne("g19_sep490_ealds.Server.Models.Role", "Role")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkflowS__RoleI__4E88ABD4");

                    b.HasOne("g19_sep490_ealds.Server.Models.Workflow", "Workflow")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("WorkflowId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkflowS__Workf__4D94879B");

                    b.Navigation("Role");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Asset", b =>
                {
                    b.Navigation("AssetCapitalizations");

                    b.Navigation("AssetLifeCycles");

                    b.Navigation("AssetLocations");

                    b.Navigation("AssetRequests");

                    b.Navigation("AssetUsages");

                    b.Navigation("DiposalRecords");

                    b.Navigation("DrepreciationRecords");

                    b.Navigation("InventoryTasks");

                    b.Navigation("MaintenaceTasks");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("RepairTasks");

                    b.Navigation("TransferRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetCategory", b =>
                {
                    b.Navigation("AssetTypes");

                    b.Navigation("InventorySessions");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetLocation", b =>
                {
                    b.Navigation("InventoryDiscrepancyActualLocations");

                    b.Navigation("InventoryDiscrepancyBookLocations");

                    b.Navigation("InventoryRecords");

                    b.Navigation("TransferRecordFromLocations");

                    b.Navigation("TransferRecordToLocations");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssetRequestRecords");

                    b.Navigation("DiposalRecords");

                    b.Navigation("MaintenaceTasks");

                    b.Navigation("Procurements");

                    b.Navigation("RepairTasks");

                    b.Navigation("TransferRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.AssetType", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("InventorySessions");

                    b.Navigation("MaintenanceTemplates");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Department", b =>
                {
                    b.Navigation("AssetLocations");

                    b.Navigation("Employees");

                    b.Navigation("InventorySessions");

                    b.Navigation("InventoryTasks");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.DepreciationPolicy", b =>
                {
                    b.Navigation("DrepreciationRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Employee", b =>
                {
                    b.Navigation("AssetUsages");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventorySession", b =>
                {
                    b.Navigation("InventoryTasks");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.InventoryTask", b =>
                {
                    b.Navigation("InventoryDiscrepancies");

                    b.Navigation("InventoryRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenaceTask", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceSchedule", b =>
                {
                    b.Navigation("MaintenaceTasks");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.MaintenanceTemplate", b =>
                {
                    b.Navigation("MaintenanceSchedules");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Procurement", b =>
                {
                    b.Navigation("AcceptanceRecords");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RepairTask", b =>
                {
                    b.Navigation("RepairRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.RequestType", b =>
                {
                    b.Navigation("AssetRequests");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Role", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("AssetLifeCycles");

                    b.Navigation("AssetRequestRecords");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Supplier", b =>
                {
                    b.Navigation("Procurements");

                    b.Navigation("RepairRecords");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.User", b =>
                {
                    b.Navigation("AcceptanceRecords");

                    b.Navigation("Approvals");

                    b.Navigation("AssetCapitalizations");

                    b.Navigation("AssetLifeCycles");

                    b.Navigation("AssetRequestRecords");

                    b.Navigation("AssetRequests");

                    b.Navigation("Assets");

                    b.Navigation("Departments");

                    b.Navigation("DiposalRecords");

                    b.Navigation("EmployeeCreatedByNavigations");

                    b.Navigation("EmployeeUsers");

                    b.Navigation("InventoryDiscrepancyActualUsers");

                    b.Navigation("InventoryDiscrepancyBookUsers");

                    b.Navigation("InventoryRecordActualUsers");

                    b.Navigation("InventoryRecordCheckedByNavigations");

                    b.Navigation("InventorySessions");

                    b.Navigation("InventoryTasks");

                    b.Navigation("MaintenaceTaskAssignToNavigations");

                    b.Navigation("MaintenaceTaskCreateByNavigations");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("Procurements");

                    b.Navigation("Roles");

                    b.Navigation("TransferRecordExecuteByNavigations");

                    b.Navigation("TransferRecordFromUsers");

                    b.Navigation("TransferRecordToUsers");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.WarehouseAsset", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.Workflow", b =>
                {
                    b.Navigation("RequestTypes");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("g19_sep490_ealds.Server.Models.WorkflowStep", b =>
                {
                    b.Navigation("Approvals");
                });
#pragma warning restore 612, 618
        }
    }
}
